@startuml
actor User

User -> View : input string
View -> ApolloServer :dispatch assistance action
Dispatcher <-- ApolloServer :response  assistance action
View --> User : input assistance
User -> View : send the name
View -> ApolloServer :generate determined Action
ApolloServer -> Network : request stock data
ApolloServer <-- Network : response stock data

@enduml

cloud Network
node ApolloServer
frame View

@startuml
actor User
agent View
agent ApolloClient
cloud Network
cloud ApolloServer
database Store

package Action{
    [action]
}
User -> View :input string
View -> Action
Action -> ApolloClient : dispatch Assistance Action
ApolloClient -> ApolloServer : Assistance Action
ApolloServer -> Network : request input assistance
Network -> ApolloServer : response input assistance

@enduml