import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Index.module.css'
// import Hamburger from '../../components/hamburger'
import Hamburger from '@/components/Hamburger'
import Tree from '@/components/Tree'
import Leaves from '@/components/Leaves'
import { useState } from 'react'

function Cancel() {
  return (<>Cancel</>)
}


function Navicon() {
  const WIDTH = 200
  const [right, setRight] = useState(-WIDTH)
  const click = () => {
    setRight(right === -WIDTH ? 0 : -WIDTH)
  }
  return (
    <div className={styles.navicon} onAbort>
      <div className={styles.hamburger} onClick={click}>
        <Hamburger width={64} height={64} />
      </div>
      <div className={styles.sidebar} style={{ width: WIDTH, right: right }} >
        <Cancel />
      </div>
    </div>
  )
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.frame}>
        <Navicon />
        <div className={styles.top}>
          <Leaves />
          <div className={styles.tree}>
            <Tree width={400} height={400} color={"#006241"} />
          </div>
        </div>
        <div className={styles.bottom}>
          <p className={styles.title}>About</p>
          <div className={styles["text-field-wrapper"]}>
            <div className={styles["text-field"]}>
              <p>2020年3月に情報系の大学を卒業後、新卒でIT企業に入社してからエンジニアやってます。</p>
              <p>このサイトでは、好きなものをつらつら書いたり作ったりしていきたいですね。</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
