version: "3.3"

volumes:
  ghost-dev-vol:

services:
  client:
    container_name: "kmd_client_dev"
    build:
      context: ../client
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/.ssh
      - ~/.vimrc:/root/.vimrc
      - ~/.vim:/root/.vim
      - ../client/src:/root/workspace/src
      - ../client/private:/root/workspace/private
      - ../client/package.json:/root/workspace/package.json
    tty: true
    network_mode: host
    extra_hosts:
      - localhost:192.168.10.14
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID

  server:
    container_name: "kmd_server_dev"
    build:
      context: ../server
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/.ssh
      - ../server:/root/workspace
    # extra_hosts:
    #   - localhost:162.251.15.115
  
  ghost:
    container_name: "kmd_ghost_dev"
    build:
      context: ../services/ghost
      dockerfile: Dockerfile
    ports:
      - "2368:2368"
    volumes:
      - ../services/ghost/data:/var/lib/ghost/content

