version: "3.3"

services:
  client-dev:
    container_name: "kmd_client_dev"
    build:
      context: ../client
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/.ssh
      - ../client:/workspace
    tty: true
    command: "/bin/bash"
    network_mode: host
    extra_hosts:
      - localhost:162.251.15.115

  server-dev:
    container_name: "kmd_server_dev"
    build:
      context: ../server
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/.ssh
      - ../server:/workspace
    extra_hosts:
      - localhost:162.251.15.115
  
  ghost-dev:
    container_name: "kmd_ghost_dev"
    build:
      context: ../services/ghost
      dockerfile: Dockerfile
    ports:
      - "2368:2368"

