version: "3.3"

volumes:
  ghost-vol:

services:
  client:
    container_name: "kmd_client"
    build:
      context: ../client
      dockerfile: Dockerfile

  server:
    container_name: "kmd_server"
    build:
      context: ../server
      dockerfile: Dockerfile

  database:
    container_name: "kmd_database"
    build:
      context: ../services/database
      dockerfile: Dockerfile
  
  ghost:
    container_name: "kmd_ghost"
    build:
      context: ../services/ghost
      dockerfile: Dockerfile
    volumes:
      - ../services/ghost/data:/var/lib/ghost/content
