version: "3.7"

services:
    ghost:
        build:
            context: ../services/ghost
            dockerfile: Dockerfile
        environment:
            url: http://localhost:2368
        ports:
            - 2368:2368