import Head from 'next/head'


import Navicon from './Navicon'
import styles from './template.module.css'
// import Hamburger from '../../components/hamburger'

import Tree from '../Tree'
import Leaves from '../Leaves'

import React, { createRef, useEffect, useRef, useState } from 'react'

const Template: React.FC<{
    title: string,
    meta: string,
    textField: React.ReactNode
}> = ({ title, meta, textField }) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.frame}>
                <Navicon />
                <div className={styles.top}>
                    <Leaves />
                    <div className={styles.tree}>
                        <Tree width={400} height={400} color={"#006241"} />
                    </div>
                </div>
                <div className={styles.bottom}>
                    {textField}
                </div>
            </div>
        </div >
    )
}

export default Template